### ISSUE TITLE
Clarification on Dev Docs > Build a Package > 3 - Hardware Build

### ISSUE THREAD

**Issue by spencerflagg** [Start9Labs/documentation#103]
https://start9.com/latest/developer-docs/build-package-example/03_hardware-compile

> Depending on the programming language or libraries used in a project, you might need to set up an environment to cross compile the executable for this runtime environment.

Would appreciate some quick examples of what sorts of libraries and languages need emulation and what sorts do not.

> We were able to easily build and run our project locally. However, Rust is one of those programming languages that needs to be cross compiled.

I think the "however" confuses me. "Our project" was built in Rust, correct? But it seemed like we didn't need to cross-compile it, as we're just installing the cross compiler now.

**Comment by ProofOfKeags** [comment]
can you specify what you mean by "Page 3 - Hardware Build", I'm having trouble locating what you're talking about.

**Comment by spencerflagg** [comment]
Clarified in the title, and added a link in the first comment.
(sorry, I guess for whatever reason I'd removed the auto-filled link) :man_shrugging:

**Comment by kn0wmad** [comment]
Hey there @spencerflagg - Can you see if our new, concise guide addresses this issue?

**Comment by kn0wmad** [comment]
Sorry @spencerflagg, I should have provided the link :P

https://docs.start9.com/latest/developer-docs/packaging

**Comment by spencerflagg** [comment]
Thanks - I'll try to run through a build tomorrow.

**Comment by spencerflagg** [comment]
@kn0wmad worked like a charm (i got past the `make` step), and the language was much better this time, thanks.
