### ISSUE TITLE
[suggestion]: Linux LAN Shared Folder - additional steps for Pop!_OS

### ISSUE THREAD

**Issue by spencerflagg** [Start9Labs/documentation#120]
On page https://start9.com/master/user-manual/backups/backup-setup/backup-linux

### Problem
Pop!_OS requires additional steps, because the Local Network Share tab in folder properties dialog is not available by default.

###  Suggest a fix
Between steps 2 and 3 in the Ubuntu instructions, add the following, for Pop!_OS users:

2.1 Install `gnome-user-share` and turn on file sharing in settings via these instructions https://support.system76.com/articles/file-sharing/ . (Local Network Share tab will still be unavailable.)
2.2 Install `nautilus-share` and enable `smbd` to show Local Network Share tab. (May need to close and re-open file manager.)
```
sudo apt install nautilus-share nautilus-admin
sudo systemctl enable smbd nmbd
sudo systemctl start smbd nmbd
```
2.3 Standard users will still not have permissions to enable sharing on a folder, so you'll have to open the file manager with `sudo` and then you can proceed with the rest of the existing steps.
```
sudo nautilus
```

**Comment by kn0wmad** [comment]
Did you try the "Other Linux" directions?  I would prefer not to have an additional set of steps specifically for PopOS

**Comment by spencerflagg** [comment]
:man_facepalming:  Ah - sorry, no, by the time I'd gotten far enough to have issues, I'd forgotten that other tab existed.

**Comment by kn0wmad** [comment]
Did that guide work on Pop?  If not, I can add a note with your directions

**Comment by spencerflagg** [comment]
The guide from System76 did not work on its own. It seemed to be only sufficient to turn sharing on globally, but not to allow arbitrary directories to be shared individually via the properties dialog. I eventually found a message board that gave me steps 2.2 and 2.3, and that got it working.

(I'm still a new enough linux user that I probably should not be trusted.)

**Comment by ProofOfKeags** [comment]
I use Pop! and I was able to successfully use the guide, maybe it's a version thing? What version are you on? I was on 21.04

**Comment by spencerflagg** [comment]
22.04
I just tried again on an another 22.04 instance.
The Local Network Share tab does not show up by Pop's guide alone.

**Comment by spencerflagg** [comment]
Ah - sorry, I think I had assumed by "the guide" you guys meant Sys76's guide, but you meant the Other Linux directions?
**I did not even try the Other Linux directions.** I used the Ubuntu directions - because in my meager experience Ubuntu directions almost always work for Pop.

**Comment by kn0wmad** [comment]
Unfortunately, it is our experience with this particular flow that *only* Ubuntu has the nice UI option.  Does not seem to work with Pop, Pure, and other Debians as far as I can tell.
