### ISSUE TITLE
docs.start9labs.com redirects to V2 docs (start9.com/0.2.x/)

### ISSUE THREAD

**Issue by BBlackwo** [Start9Labs/documentation#127]
I noticed [a few links](https://github.com/Start9Labs/embassy-os/search?q=docs.start9labs.com) that point to [docs.start9labs.com](https://docs.start9labs.com) which then redirects to the [v2 docs](https://start9.com/0.2.x/).

It's also the link on this repo:

![Screenshot from 2022-05-27 12-52-12](https://user-images.githubusercontent.com/7598058/170619407-8cbb4961-906f-4869-8da8-49cd2a7f0a49.png)

You may want to update that redirect to the latest docs.

**Comment by kn0wmad** [comment]
Thank you for the report.  I have fixed the repo link.  I will investigate further, but I believe the reason that docs.start9labs.com redirects to the v2 docs is because that link is used in the v0.2 UI.  Good eye, and thanks again :)

**Comment by BBlackwo** [comment]
Makes sense. Maybe the redirect can be updated once v0.2 is no longer being used then?

**Comment by kn0wmad** [comment]
These links will not be used anymore.  https://github.com/Start9Labs/embassy-os/pull/1905 will fix the references in question.  Thank you for the report @BBlackwo
