### ISSUE TITLE
Fix Brave LAN Connecting Guide

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#167]
Missing step and screenshot as Brave menus have changed

**Comment by kn0wmad** [comment]
There is a larger issue here in regard to Windows LAN connections.... it now appears that browsers will pop-up a window for system-wide cert support, which is objectively better, but breaks all our guides

**Comment by gStart9** [comment]
pull/175 takes care of this

**Comment by kn0wmad** [comment]
Closed by #175
