### ISSUE TITLE
[update]: v0.3.3 Audit and Refactoring

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#194]
UPDATE SCREENSHOTS WHEN OUT OF DATE (i.e., missing connection status bar, containing old menu items, etc)

### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

- [x] x86 - @kn0wmad 
    - [x] DIY - entire refactor/simplification

- [x] Kiosk Mode  @gStart9 
    - [x] Initial Setup (@gStart9)
    - [x] FAQ - can I use a monitor/keyboard? (@gStart9)
    - [x] User Manual (feature)
    - [x] Comparison doc - @kn0wmad 

- [x] Install Wizard - @kn0wmad 
    - [x] DIY
    - [x] Reflash (change password)
    - [x] FAQ - installing to x86 machines (@gStart9)
    - [x] https://docs.start9.com/latest/user-manual/updating#manual-update-by-re-flashing

Related, [add/refactor language around restore/attach/recover](https://github.com/Start9Labs/documentation/issues/145)

- [x] Marketplace Redesign - @gStart9 
    - [x] FAQ
    - [x] UI Walkthrough
    - [x] Alt Marketplaces

- [x] Reordering Gone - @BitcoinMechanic 
    - [x] Customize
    - [x] FAQ?

- [x] Auto check updates Gone - @BitcoinMechanic 
    - [x] Updating EmbassyOS

- [x] "Updates" Tab  - @BitcoinMechanic 
    - [x] UI Walkthrough
    - [x] https://docs.start9.com/latest/user-manual/managing-services#updating-a-service

- [x] Preferences page removed - @kn0wmad 
    - [x] UI Walkthrough
    - [x] Customize

- [x] Connection Status Bar - @BitcoinMechanic 
    - [x] UI Walkthrough
    - [x] Screenshot Audit

- [x] Migrate drives - @kn0wmad 
    - [x] Address #145

- [ ] #242

- [ ] #243
- [x] Replace all instances of "LAN Shared Folder" with "Network Folder" - defined as a folder on another computer that is connected to the same network as your embassy - @BitcoinMechanic  

- [x] Add note to Windows backup setup that online/365 accounts may not work - @kn0wmad

**Comment by kn0wmad** [comment]
Add any new videos as relevant

**Comment by BitcoinMechanic** [comment]
going to wait for community marketplace to be put back up before I do the updates tab

**Comment by kn0wmad** [comment]
> going to wait for community marketplace to be put back up before I do the updates tab

Do not wait on any of this - we don't have an ETA on that and we need this refresh done right away
