### ISSUE TITLE
[bug]: New make preview error in documentation

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/documentation#204]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.6

### Browser

Firefox

### Browser Version

106

### Current Behavior

`make preview` produces this:

![image](https://user-images.githubusercontent.com/106188942/203186573-9c02a1b2-8483-4b6b-979c-a10577bbabb1.png)

### Expected Behavior

Expect make preview to be successful.

### Steps to Reproduce

download documentation repo
```
git clone https://github.com/start9labs/documentation.git
cd documentation/site
make preview
```

**Comment by gStart9** [comment]
Does this error make any sense?  I didn't change anything!  dunno what's wrong.

**Comment by kn0wmad** [comment]
> Does this error make any sense? I didn't change anything! dunno what's wrong.

Check your `node` version - If using NVM, mine always changes itself to latest and I have to put it back on 16.11

**Comment by gStart9** [comment]
💯 ty
