### ISSUE TITLE
[bug]: Search for a word on the docs site does not return all pages where the word occurs

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/documentation#210]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.10

### Browser

Firefox

### Browser Version

106

### Current Behavior

[This page](https://docs.start9.com/latest/user-manual/connecting/connecting-lan/lan-os/lan-windows) contains the word Bonjour multiple times yet does not show up when I search for bonjour on https://docs.start9.com:

![image](https://user-images.githubusercontent.com/106188942/204929405-1e556742-4685-4037-afa2-a236f639fbcc.png)

### Expected Behavior

Expect bonjour search to turn up all docs instances of bonjour

### Steps to Reproduce

#. go to https://docs.start9.com
#. Search for bonjour or Bonjour
#. Frown

**Comment by elvece** [comment]
Started looking into this today, tried a few solutions to update the search, but nothing working yet.

**Comment by elvece** [comment]
Fixed:
<img width="1724" alt="Screenshot 2023-07-27 at 6 37 08 PM" src="https://github.com/Start9Labs/documentation/assets/12953208/104e0564-8296-434c-9cc2-ac1ad42eaf54">
