### ISSUE TITLE
[feat]: Add guide for importing LAN cert to Thunderbird

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#235]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Self-explanatory

### Describe the Use Case

For Nextcloud and possibly Cryptpad to sync contacts and calendars

**Comment by gStart9** [comment]
Fix: #316

**Comment by kn0wmad** [comment]
Closed by #316
