### ISSUE TITLE
[maintenance] Chrome seems to have changed how certificates are added

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#237]
Investigate and update LAN connecting guide for Chrome

**Comment by gStart9** [comment]
I inspected this on Chromium on linux -- the guide is up to date.  There may be a difference on Windows, which I'll test Wednesday and update the guide if necessary.

**Comment by gStart9** [comment]
Should be fixed up by https://github.com/Start9Labs/documentation/pull/274
