### ISSUE TITLE
[feat] Find out if Linux/Windows can use system proxy for FF

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#252]

**Comment by k0gen** [comment]
Linux is going to be dependent on the distribution being used. I can confirm this is working on elementarOS 6.1 and 7.0

![Screenshot from 2023-01-02 10 52 04](https://user-images.githubusercontent.com/3606313/210216172-0db411f5-71dc-44cb-9dca-2ab51da1ee64.png)

**Comment by kn0wmad** [comment]
> Linux is going to be dependent on the distribution being used. I can confirm this is working on [elementaryOS](https://elementary.io/) 6.1 and 7.0 ![Screenshot from 2023-01-02 10 52 04](https://user-images.githubusercontent.com/3606313/210216172-0db411f5-71dc-44cb-9dca-2ab51da1ee64.png)

Do you say this because of differences in DEs?  If so - I assume elementary is using Gnome, which is a common one, we can test some others.

**Comment by gStart9** [comment]
I entered mine on Debian 11 but it does not work:
![image](https://user-images.githubusercontent.com/106188942/210291648-2cfcdfab-6625-44b7-8a19-da418ab1e668.png)

Chrome and ssh don't know how to resolve .onion after that :(

**Comment by gStart9** [comment]
This apparently is not possible on windows.  You can set a system-wide proxy but only of certain types that are not a PAC file where determining which proxy is picked is based on the URL.

**Comment by kn0wmad** [comment]
So it seems that only certain distros and macos are capable of this.  We can make guides for those and hopefully others will follow suit in future.

**Comment by kn0wmad** [comment]
Closing for now
