### ISSUE TITLE
Issue in page Running Tor on Windows

### ISSUE THREAD

**Issue by JulioAviles** [Start9Labs/documentation#262]
I would like to report an issue in page https://docs.start9.com/master/user-manual/connecting/connecting-tor/tor-os/tor-windows

### Problem
I have not been able to use tor in windows, I have this problem where these solutions are given without success for me. https://www.youtube.com/watch?v=9Tt0YALciZg
I came across your tutorial and I thought it would be a solution but I'm still in the same situation, I wanted to let you know so if you had a solution, update your guide, by the way, excellent page, I'll be watching your work, regards!
###  Suggest a fix
I would like to have one, but unfortunately not. :(

**Comment by kn0wmad** [comment]
Hi there - thank you for the report.  I have just run through a fresh setup to confirm that there are no errors in the guide.  Please contact our support team so we can help you fix your configuration and get you online :)

You can find the possible contact options here: https://docs.start9.com/latest/support/contact
