### ISSUE TITLE
Issue in page Setting Up Organizations

### ISSUE THREAD

**Issue by bittog9** [Start9Labs/documentation#269]
I would like to report an issue in page https://docs.start9.com/master/user-manual/service-guides/vaultwarden/vaultwarden-organizations

### Problem 
In section 4 the new user does not show under "Accepted" but shows under invited. I had this issue but had SMTP on but not configured correctly.  

###  Suggest a fix 
Maybe have a warning message "If users do not show under "Accepted" and are in the invited section make sure you have not got SMTP configuration turned on from the admin page.

**Comment by gStart9** [comment]
fixed by https://github.com/Start9Labs/documentation/pull/280
