### ISSUE TITLE
[maint] Update Flashing Guide for Pro Users

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#278]
Final couple steps refer to setting "Legacy boot," which is not necessary on Pro devices

**Comment by BitcoinMechanic** [comment]
We don't have a guide that's just for the pro - it's broken out Pi/x86/firmware. Want a fourth breakout for just the Pro?

**Comment by kn0wmad** [comment]
> We don't have a guide that's just for the pro - it's broken out Pi/x86/firmware. Want a fourth breakout for just the Pro?

Probably not since only a couple notes need to be made

**Comment by BitcoinMechanic** [comment]
OK will get this done asap

**Comment by BitcoinMechanic** [comment]
Will be fixed by https://github.com/Start9Labs/documentation/pull/282
