### ISSUE TITLE
[update] Improve Password Reset Guide

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#279]
- [ ] Add a step to plug in flash drive for Pro users, and indicate how to boot into it (i.e. you need a keyboard and monitor and a keypress)
- [ ] Edit final steps of x86 flashing guide with similar language

**Comment by BitcoinMechanic** [comment]
Are you sure this requires a keypress? I recall reflashing my Pro simply by having the USB inserted and turning it on.

**Comment by kn0wmad** [comment]
It does not, it's automatically detecting drive under the firmware that we ship

**Comment by BitcoinMechanic** [comment]
I don't believe so, @dr-bonez has confirmed that screen and keyboard aren't necessary.
