### ISSUE TITLE
Issue in page Lightning Integrations

### ISSUE THREAD

**Issue by Ciugam** [Start9Labs/documentation#325]
I would like to report an issue in page https://docs.start9.com/master/user-manual/service-guides/lightning/lightning-integrations

### Problem
Zeus since version 0.6.0 (2022-02), supports core-lightning connection to embassy node, and since 0.6.5 (2022-07) supports spark qr connection.
(I've tested them and they both work fine)
###  Suggest a fix
you should edit Zeus section to be compatible also with CLN and Spark.

Thanks.

**Comment by kn0wmad** [comment]
Thanks for the report, we'll get this fixed alongside #240 in a forthcoming update

**Comment by Ciugam** [comment]
Glad to help!

**Comment by kn0wmad** [comment]
I'm going to leave this open until addressed

**Comment by BitcoinMechanic** [comment]
FIxed by - https://github.com/Start9Labs/documentation/pull/327

**Comment by kn0wmad** [comment]
Closed by #354
