### ISSUE TITLE
Issue in page Flashing (Raspberry Pi)

### ISSUE THREAD

**Issue by jherman89** [Start9Labs/documentation#374]
I would like to report an issue in page https://docs.start9.com/master/user-manual/flashing/flashing-pi

### Problem

There is no checksum for the embassy 'tar' file on the github assets page.

###  Suggest a fix

Include a checksum for the embassy 'tar' file on the github assets page.

**Comment by kn0wmad** [comment]
DIY and Flashing guides will be revamped.  In the meantime, get and verify the checksum for the extracted image instead, which is provided and preferred.
