### ISSUE TITLE
0.3.0 Service packaging guide

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/documentation#38]
Create 0.3.0 compliant service packaging guide that is complete and enough to get someone with non-zero but minimal docker experience to the point where they can successfully deploy an s9pk to the Embassy

**Comment by kn0wmad** [comment]
Currently in progress here (https://github.com/Start9Labs/embassy-os/pull/439) in 'walk-through' style.  Can be added to documentation as well, existing service packaging guide will probably just be modified.

**Comment by ProofOfKeags** [comment]
Do you think that this ticket should me moved to the embassy-os repo? Does it make sense to have this separate docs repo at all?

**Comment by kn0wmad** [comment]
This docs repo is mainly for the docs.start9.com documentation.  I don't think it necessarily needs to be moved, but I don't feel strongly about not moving it either.  I think my idea was to have the walk-through in the EOS repo, and expound upon it here in the 0.3.0 Service Packaging Guide section of the docs

**Comment by kn0wmad** [comment]
This has now had several drafts and revisions, closing for now in lieu of routine updates going forward
