### ISSUE TITLE
[docs]: Wrong address given in docs (self-build) for startup page

### ISSUE THREAD

**Issue by jonnymarshall** [Start9Labs/documentation#385]
Startup page should be http://start.local/ according to the [docs](https://github.com/Start9Labs/start-os/tree/master/build)

However the actual startup page is http://embassy.local/ and not http://start.local/ (even on the latest version).

I thought there was an error as start.local did not work. I was about to give up until I watched a [BTC Sessions tutorial](https://www.youtube.com/watch?v=DKBJ3_3ZomU) which said to go to http://embassy.local/. And this worked.

**Comment by kn0wmad** [comment]
We are in flux at the moment and an update is imminent which will see the http://start.local change.  Please pardon our construction dust.
