### ISSUE TITLE
[maint] CA Names Are Now `adjective-noun.local.crt`

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#399]

**Comment by gStart9** [comment]
The (at least Linux) CA guide is fixed by this PR:
https://github.com/Start9Labs/documentation/pull/398/files

**Comment by gStart9** [comment]
^The Linux fix went in today (thanks @kn0wmad).

Still in need of updating:

https://docs.start9.com/latest/user-manual/connecting/connecting-lan/lan-os/lan-mac
https://docs.start9.com/latest/user-manual/connecting/connecting-lan/lan-os/lan-windows (screenshot from step 9)
https://docs.start9.com/latest/user-manual/connecting/connecting-lan/lan-os/lan-android (not sure - review required)

**Comment by kn0wmad** [comment]
Mac and Android will be fixed by #424 - still need screenshot for windows

**Comment by kn0wmad** [comment]
Windows will be fixed by #427 , which will close this issue
