### ISSUE TITLE
0.3.0 DIY Guide

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/documentation#40]
Update the DIY guide for EmbassyOS 0.3.0

**Comment by kn0wmad** [comment]
Currently in progress @ https://github.com/Start9Labs/embassy-os/pull/472

Will adapt into Documentation upon completion

**Comment by kn0wmad** [comment]
WIP @ #49

**Comment by ProofOfKeags** [comment]
Blocked on deploying docs.

**Comment by kn0wmad** [comment]
I would argue that this is complete and can be moved to review
