### ISSUE TITLE
Issue in page Flashing (x86_64)

### ISSUE THREAD

**Issue by Brettinthewoods** [Start9Labs/documentation#414]
I would like to report an issue in page https://docs.start9.com/master/user-manual/flashing/flashing-x86

### Problem
Missing a step between step 7 and step 8 of actually installing StartOS on the device.

###  Suggest a fix
Step 8: Plug the USB drive into the device and power on. The initial boot sequence will install StartOS on the device. Follow any on-screen instructions. After install is complete, remove your USB drive. (The tip for Step 7 should be moved to Step 8)
The current step 8 should become Step 9.

**Comment by kn0wmad** [comment]
Will be closed by #418
