### ISSUE TITLE
[maint] Replace Backup/Restore Screenshots

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#431]
Still referencing eOS

**Comment by B1ackSwan9** [comment]
I made the screenshots if you can use them
![restore0](https://github.com/Start9Labs/documentation/assets/137729263/1327750f-001a-4173-8550-12a072958816)
![restore1](https://github.com/Start9Labs/documentation/assets/137729263/52202c3b-3e7a-443a-90b6-f83bc1aa7a91)
![restore2](https://github.com/Start9Labs/documentation/assets/137729263/c526b791-0bbc-4b65-b5fb-b7d6f1652516)
![restore3](https://github.com/Start9Labs/documentation/assets/137729263/4e42eaaa-ac20-4312-8a1b-0b7b0b3e6a25)

**Comment by kn0wmad** [comment]
Complete in #470 - thanks @B1ackSwan9 and @jadijadi
