### ISSUE TITLE
[issue] Alby CLN guide is out of date - refers to CLN nodeID which is no longer in properties

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/documentation#447]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Phone/tablet

### Device OS

Linux

### Device OS Version

6.10

### Browser

Firefox

### Browser Version

115

### Current Behavior

https://docs.start9.com/latest/user-manual/service-guides/lightning/alby-cln

Step 9 refers to NodeID in CLN which is no longer real.

### Expected Behavior

User expects a nodeid based on the screenshot.

### Steps to Reproduce

Follow step 9 here:
https://docs.start9.com/latest/user-manual/service-guides/lightning/alby-cln

**Comment by Dominion5254** [comment]
Node ID broken out as separate property with https://github.com/Start9Labs/cln-startos/pull/95
