### ISSUE TITLE
[bug] Fix Documentation Contribution Page

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#449]
GitHub flow has changed, breaking [the guide](https://docs.start9.com/latest/developer-docs/documentation)

**Comment by jadijadi** [comment]
Hi guys. Was following the project for some time and decided to do some contributions. Started with this one but I (and most probably most newcomers) do not have "Ask for review" cog when creating the PR. Should I skip that step altogether? If not, one of you guys (who have access to the "ask for review from specific user" rights have to create the screenshots). In addition, newbies won't have the exact same experience with your screenshots.

my suggestion? I create it without the "ask for review".  waiting for your comments.

**Comment by kn0wmad** [comment]
> Hi guys. Was following the project for some time and decided to do some contributions. Started with this one but I (and most probably most newcomers) do not have "Ask for review" cog when creating the PR. Should I skip that step altogether? If not, one of you guys (who have access to the "ask for review from specific user" rights have to create the screenshots). In addition, newbies won't have the exact same experience with your screenshots.
> 
> my suggestion? I create it without the "ask for review". waiting for your comments.

We have a PR up for this in #464 - it should provide better clarity

**Comment by kn0wmad** [comment]
Closed by $464
