### ISSUE TITLE
Secondary Menu (on the right) links when visited, does not show the section title on main frame

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/documentation#45]
Section Title positioning is too high in the main frame, and is hidden when links are visited.

Browser: FireFox
OS: PopOS

**Comment by kn0wmad** [comment]
#49 v0.3 docs overhaul should fix this

**Comment by kn0wmad** [comment]
This should not be happening on the new theme.  Closing for now, if this comes up again, we can re-open
