### ISSUE TITLE
[maint] Breakout Thunderbird Nextcloud Integration Guide to Integrations

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#452]

**Comment by 13Homer13** [comment]
It woudl have to be removed from nextcloud device setup mac/linux/win and moved to integrations under Jopli. Right?

**Comment by kn0wmad** [comment]
It would go under Integrations alongside Joplin, yes

**Comment by 13Homer13** [comment]
Ok I can move things around.

**Comment by kn0wmad** [comment]
Closed by #501
