### ISSUE TITLE
Out-dated info in page Initial Setup video

### ISSUE THREAD

**Issue by Satoshiroll** [Start9Labs/documentation#456]
I would like to report an issue in page https://docs.start9.com/master/user-manual/getting-started/initial-setup

### Problem
Video instructs user to go to http://embasy.local.

###  Suggest a fix
Create a new updated video.
Temporary fix would be to highlight a notation above the video clarifying the address.

**Comment by kn0wmad** [comment]
Closing as duplicate of #446 - please check existing issues before opening a new one
