### ISSUE TITLE
Issue on page /misc-guides/tor-os/windows.html

### ISSUE THREAD

**Issue by kamadom** [Start9Labs/documentation#46]
Website instructions for Running Tor on Windows as a service result in errors, because a space is required between the equal sign and the value.  Please correct the following;  
WRONG:     sc create tor start=auto binPath="<PATH TO>\Browser\TorBrowser\Tor\tor.exe -nt-service"
CORRECT:   sc create tor start= auto binPath= "<PATH TO>\Browser\TorBrowser\Tor\tor.exe -nt-service"
Location:    https://docs.start9.com/misc-guides/tor-os/windows.html  Your issue content here.

**Comment by kn0wmad** [comment]
So I tested this on a Windows machine and received no error using the command without spaces.  I'm not sure why you were unable to use the command.  What version of Windows are you on?

**Comment by kamadom** [comment]
Windows 7 Ultimate Service Pack 1.  Using cmd as administrator
See screenshot attached to my earlier message  The error messages clearly
says a space is required.  Try it both ways on your version of Windows.

I will replicate the error once again, but must be done later in the
day, as I have pressing work right now..

**Comment by kn0wmad** [comment]
I saw the screenshot, but again, the error does not occur with the command in our documentation.  It is perhaps not perfect form, but functional.  This is on Windows 10.  I wonder if this is an artifact of Windows 7?  Do you have a Win10 machine by chance?  No rush, we appreciate your help

**Comment by ProofOfKeags** [comment]
If both work on Win10, and only one works on Win7, as long as the syntax hasn't been officially deprecated we should probably recommend the way that has larger coverage.

**Comment by kamadom** [comment]
Ok, thanks.

**Comment by kn0wmad** [comment]
> If both work on Win10, and only one works on Win7, as long as the syntax hasn't been officially deprecated we should probably recommend the way that has larger coverage.

Agreed - @kamadom do you want to open a PR and I'll get it merged in?

**Comment by kamadom** [comment]
Yes, I agree.  Normally only a member of the organization that owns the
repository can open a PR for organization-owned repositories.  You, as a
team developer, can open a pull request.  I am just a customer and project
supporter.

This annoying issue was why I alerted the team to the problem with Windows
7, including screenshots specifying the command syntax errors (a space
required after the commands), and created a fork.  I believe the base
branch is where changes should be applied.

On a different Windows 7 machine a few moments ago, I have just repeated
the command error syntax, followed by the suggested solution that indeed
works (see attached screenshot).  This is running Windows 7 Ultimate,
Service Pack 1

I will try the same sequence of commands on a Windows 10 computer and
report what results.

Here is the text copied from the Administrator Command Prompt showing
failure followed by success:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>sc create tor start=auto
binPath="C:\Users\Charles\Desktop\T
or Browser\Browser\TorBrowser\Tor\tor.exe -nt-service"
DESCRIPTION:
        Creates a service entry in the registry and Service Database.
USAGE:
        sc <server> create [service name] [binPath= ] <option1> <option2>...

OPTIONS:
NOTE: The option name includes the equal sign.
      *A space is required between the equal sign and the value*.
 type= <own|share|interact|kernel|filesys|rec>
       (default = own)
 start= <boot|system|auto|demand|disabled|delayed-auto>
       (default = demand)
 error= <normal|severe|critical|ignore>
       (default = normal)
 binPath= <BinaryPathName>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <Dependencies(separated by / (forward slash))>
 obj= <AccountName|ObjectName>
       (default = LocalSystem)
 DisplayName= <display name>
 password= <password>

C:\Windows\system32>sc create tor start= auto binPath=
"C:\Users\Charles\Desktop
\Tor Browser\Browser\TorBrowser\Tor\tor.exe -nt-service"
[SC] CreateService SUCCESS

C:\Windows\system32>
C:\Windows\system32>sc start tor

SERVICE_NAME: tor
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE,
IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 12696
        FLAGS              :

C:\Windows\system32>

**Comment by kn0wmad** [comment]
@kamadom - I'd be happy to do a PR for you, but would like for you to get the credit for the fix.  You should be able to submit a PR from your fork, as this repo is public.  Happy to help if you have any issues with this.

**Comment by ProofOfKeags** [comment]
I think it is more important to fix the issue than to get contribution credit to someone who has stated he'd like us to do it.

**Comment by kn0wmad** [comment]
Fixed in latest commit to Master, closing.

**Comment by kamadom** [comment]
Hi Keagan,

Happy Thanksgiving Holiday!  Thanks for handling this.  I have been swamped
with assisting the producing of a benefit concert series and, of course,
family arriving for Thanksgiving.

To thank you for all you are doing at Start9, here is something special
that I can offer you.  I own vacation rentals in Baja California Sur, just
north of Los Cabos.  After the dust settles from your rollout of Embassy
0.3.0 you will likely be more than ready for another holiday.  Should you
want to have a very low cost vacation to Mexico, you are welcome to stay in
one of our units for 50% off our online rates at Airbnb, Booking.com, or
Evolve.  Check our units and availability at https://oasisbcs.com/ or
https://www.airbnb.com/rooms/18916570   Make a screenshot of the total
price for the dates you want, but do not book online.  Contact me directly
at this email address with subject "Keagan50" and the screenshot.  I will
block the dates you wish for you at our agreed discount rate.  Bring your
significant other, or up to 3 other family or friends for our large two
bedroom unit.

Cheers!  Charles

**Comment by ProofOfKeags** [comment]
Hi Charles. Thank you for your offer! I'll be sure to let you know when we plan to take you up on it.
