### ISSUE TITLE
[bug]: Page not found 404 in DIY > DIY rasPi > flashing redirecting to flashing guide

### ISSUE THREAD

**Issue by 13Homer13** [Start9Labs/documentation#460]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

Ventura 13.4.1

### Browser

Firefox

### Browser Version

116.0

### Current Behavior

Getting 404 page not found in  doc page: https://docs.start9.com/latest/user-manual/flashing/flashing-pi

### Expected Behavior

Page with flashing pi guide.

### Steps to Reproduce

Click link.

**Comment by gStart9** [comment]
There was a big re-arrangement of the menu layout and with it, most URLs changed.  That particular guide is now here:
https://docs.start9.com/latest/guides/flashing/flashing-pi

@kn0wmad How easy is it to put in redirects from the old URLs?  Here's a bunch that now 404 and don't redirect and where they should redirect to:
```
https://docs.start9.com/latest/user-manual/service-guides/bitcoin/bitcoin-cli | https://docs.start9.com/latest/guides/service-guides/bitcoin/bitcoin-integrations
https://docs.start9.com/latest/user-manual/service-guides/bitcoin/blockchain-copy | https://docs.start9.com/latest/guides/service-guides/bitcoin/blockchain-copy
https://docs.start9.com/latest/user-manual/service-guides/bitcoin/bitcoin-integrations | https://docs.start9.com/latest/guides/service-guides/bitcoin/bitcoin-integrations
https://docs.start9.com/latest/user-manual/reset-password | https://docs.start9.com/latest/guides/reset-password
https://docs.start9.com/latest/user-manual/initial-setup | https://docs.start9.com/latest/user-manual/getting-started/initial-setup
https://docs.start9.com/latest/user-manual/flashing/flashing-pi | https://docs.start9.com/latest/guides/flashing/flashing-pi
https://docs.start9.com/latest/user-manual/flashing/flashing-x86 | https://docs.start9.com/latest/guides/flashing/flashing-x86
https://docs.start9.com/latest/user-manual/flashing/flashing-firmware | https://docs.start9.com/latest/guides/flashing/flashing-firmware
https://docs.start9.com/latest/support/faq/faq-embassy | https://docs.start9.com/latest/support/faq/faq-startos
```

I noticed several that do redirect, including quite a few of the more important ones, but I agree it would be nice to have comprehensive redirects so that anyone looking back at an old TG post or link posted elsewhere can still get where they need to go.  Assuming these are easy to put in place once compiled (Is that true @kn0wmad?), can you come up with a comprehensive list of which ones should redirect, @13Homer13?

**Comment by 13Homer13** [comment]
This is from DIY > DIY rasPi > flashing.

**Comment by kn0wmad** [comment]
> There was a big re-arrangement of the menu layout and with it, most URLs changed. That particular guide is now here: https://docs.start9.com/latest/guides/flashing/flashing-pi
> 
> @kn0wmad How easy is it to put in redirects from the old URLs? Here's a bunch that now 404 and don't redirect and where they should redirect to:
> 
> ```
> https://docs.start9.com/latest/user-manual/service-guides/bitcoin/bitcoin-cli | https://docs.start9.com/latest/guides/service-guides/bitcoin/bitcoin-integrations
> https://docs.start9.com/latest/user-manual/service-guides/bitcoin/blockchain-copy | https://docs.start9.com/latest/guides/service-guides/bitcoin/blockchain-copy
> https://docs.start9.com/latest/user-manual/service-guides/bitcoin/bitcoin-integrations | https://docs.start9.com/latest/guides/service-guides/bitcoin/bitcoin-integrations
> https://docs.start9.com/latest/user-manual/reset-password | https://docs.start9.com/latest/guides/reset-password
> https://docs.start9.com/latest/user-manual/initial-setup | https://docs.start9.com/latest/user-manual/getting-started/initial-setup
> https://docs.start9.com/latest/user-manual/flashing/flashing-pi | https://docs.start9.com/latest/guides/flashing/flashing-pi
> https://docs.start9.com/latest/user-manual/flashing/flashing-x86 | https://docs.start9.com/latest/guides/flashing/flashing-x86
> https://docs.start9.com/latest/user-manual/flashing/flashing-firmware | https://docs.start9.com/latest/guides/flashing/flashing-firmware
> https://docs.start9.com/latest/support/faq/faq-embassy | https://docs.start9.com/latest/support/faq/faq-startos
> ```
> 
> I noticed several that do redirect, including quite a few of the more important ones, but I agree it would be nice to have comprehensive redirects so that anyone looking back at an old TG post or link posted elsewhere can still get where they need to go. Assuming these are easy to put in place once compiled (Is that true @kn0wmad?), can you come up with a comprehensive list of which ones should redirect, @13Homer13?

@elvece has done several redirects recently - CC'ing her to check these ones out.  Be sure you are visiting the latest docs page as some links were recently fixed.  I'll publish the latest in the morning along with @13Homer13's big nextcloud PR

**Comment by elvece** [comment]
These should now all be properly redirected. Please lmk if any further inconsistencies appear!
