### ISSUE TITLE
Persist Tor URL

### ISSUE THREAD

**Issue by elvece** [Start9Labs/documentation#5]
Add logic to keep the domain in tor if visited from the tor website address.

**Comment by ProofOfKeags** [comment]
Is this about where the documentation is hosted or what is *in* the documentation?

**Comment by elvece** [comment]
I think this was about where it was hosted, and that is resolved.
The only issue I can see _in_ the documentation, is that there is no logic implemented for links _back_ to the main website persisted over Tor - it always goes to start9.com

**Comment by kn0wmad** [comment]
This will be closed by #49 - one exception will be the Marketplace.  Once a tor-only marketplace is available, will need to check that there is logic to stay in tor when visiting the market

**Comment by kn0wmad** [comment]
Closing for now as not currently relevant in this repo
