### ISSUE TITLE
[Typo]: Redundant tip on mac network folder guide

### ISSUE THREAD

**Issue by B1ackSwan9** [Start9Labs/documentation#507]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

Ventura

### Browser

Firefox

### Browser Version

117

### Current Behavior

Simple typo: the tip located at step 8 of the guide is redundant. The same tip is mentioned twice.

### Expected Behavior

only one needed

### Steps to Reproduce

go to https://docs.start9.com/latest/guides/device-guides/dg-mac/backup-mac

### Anything else?

![BEE969F8-401E-478E-9259-40BC81F40DC4](https://github.com/Start9Labs/documentation/assets/137729263/53671b8b-9c29-4c8f-a295-a74f43705392)

**Comment by kn0wmad** [comment]
Fixed by #508
