### ISSUE TITLE
[feat] SMTP Guides

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#510]
Under Misc Guides

https://mariushosting.com/synology-activate-gmail-smtp-for-docker-containers/

**Comment by jadijadi** [comment]
Ouuch. Just finished "How to enable SMTP on Gmail" and while sending the PR, saw that you also added a page. 
I've created a page for Gmail with screenshots. What is your suggestion? I can just discard it or we can create a page with tabs for gmail & amazon. Keep mine on gmail and link to Amazon on the amazon tab. later we can create our own amazon doc. 

Or I can discard mine. not a big deal. What is your suggesion?

**Comment by kn0wmad** [comment]
My apologies, I should have closed this issue.  We'll go with your upgraded guide - I will review today.  Closing this issue as complete
