### ISSUE TITLE
Android permission issue when accessing proxy.pac file

### ISSUE THREAD

**Issue by RhynoTech** [Start9Labs/documentation#52]
OS: CalyxOS
Android Version: 11

After following the guide on the Start9 docs for setting up Firefox to use the Tor proxy I ran into an issue when trying to use the local proxy.pac file.

As mentioned in the docs I referenced the file like so:

`file:///storage/emulated/0/Download/proxy.pac`

This didn't seem to work and after reaching out to the CalyxOS matrix room about the issue they said Android had changed the security model and to try putting the file in the apps data directory:

`file:///storage/emulated/0/Android/data/org.mozilla.firefox_beta/files/Download/proxy.pac`

This did require a non stock file explorer as the stock one wouldn't allow me to copy files into the above directory. I chose to use Explorer by Speed Software but I'm sure others would work as well.

I haven't been able to confirm if this is related to CalyxOS specifically as I don't have another Android phone to test with but it sounded like this is an issue with all newer Android versions.

Would be good to confirm if this is the case and update the documentation to avoid confusion.

**Comment by kn0wmad** [comment]
Thank you, this will be addressed in #49

**Comment by kn0wmad** [comment]
I tested this on GrapheneOS without issue (as written in docs).  I have added a note to the new documentation for CalyxOS users.  Additional testing by other Android versions (Lineage, vanilla Android 12+) would be helpful.

**Comment by kn0wmad** [comment]
This seems to be related to how new a device is.  Had a Pixel 6 Graphene user encounter the same issue and the given fix worked.  @Rhyno88 are you on a newer model device?

**Comment by Rhyno88** [comment]
I am using a Pixel 5. Interesting that its hardware dependent and not OS. Maybe something to do with the Titan chip. Although this is also on the Pixel 3 and 4 phones, not sure about other Android phones though.

**Comment by kn0wmad** [comment]
For now I'm documenting as required on 'some newer phones' until we get more feedback from users.  Thanks again for the report, this will be closed when new docs page is completed and published

**Comment by cryptodread** [comment]
I just tested it on a Pixel 5a with CalyX and the fix worked for me. Thanks!
