### ISSUE TITLE
Issue in page Alby

### ISSUE THREAD

**Issue by julian-source-1** [Start9Labs/documentation#524]
I would like to report an issue in page https://docs.start9.com/0.3.4.4/guides/service-guides/lightning/alby-cln

### Problem
Documentation still recommends to download Spark in order to acquire a Rune, even though it is being removed from the Community registry according to [Matt Hill](https://t.me/start9_labs/1/75954). The [link to Spark listed in step 10](https://marketplace.start9.com/marketplace/spark-wallet) also opens up to an empty page. 

###  Suggest a fix
List a different method for acquiring a Rune to set up Alby,

**Comment by kn0wmad** [comment]
This will be fixed by #516 - thank you for reporting :)

**Comment by kn0wmad** [comment]
Fixed by #570
