### ISSUE TITLE
[bug]: Documentation project setup issues

### ISSUE THREAD

**Issue by michaelWuensch** [Start9Labs/documentation#540]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Linux Manjaro

### Browser

Firefox

### Browser Version

not relevant

### Current Behavior

I want to contribute to the documentation, but I have problems setting up the project and therefore cannot preview my changes before doing a commit.

I installed python3, pyenv & python poetry

![image](https://github.com/Start9Labs/documentation/assets/15313630/822f6454-2e8d-4ac4-9767-a412b867f383)

![image](https://github.com/Start9Labs/documentation/assets/15313630/1f32a065-9fef-4410-b638-bb2e2aea99dd)

Any ideas?

### Expected Behavior

make clean && make preview
should work

### Steps to Reproduce

follow the build instructions

**Comment by kn0wmad** [comment]
Hi there, would you be able to come into our [Matrix or Telegram](https://start9.com/contact) so I can help you debug this?  It will go a lot faster with a quick back and forth.  Seems like something has likely changed with one of these build tools.  We'll be moving to a simpler system after v0.4.

**Comment by kn0wmad** [comment]
Should be fixed by #555
