### ISSUE TITLE
[update] Add Misc Guide for Tor Browser

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#552]
Enterprise roots must be enabled, possibly more depending on OS.  Needs more testing across devices

**Comment by kn0wmad** [comment]
Will be separate for Mac, Linux, etc

**Comment by gStart9** [comment]
#578 is enough for mac -- the Firefox guide is identical

Linux is not so easy -- Linux Firefox relies on its own trust store and will never pay attention to the OS trust store unless you manually point to p11-kit by adding a "Security Device" (see the Debian/Ubuntu tab [here](https://docs.start9.com/0.3.5.x/misc-guides/ca-ff)). Additionally, TorBrowser (on all platforms) doesn't allow importing of individual CA certs, no matter the path.  On Linux, it seems people either need to use Firefox with Tor configured, or click through the untrusted SSL warning on TorBrowser, at least for now.

**Comment by kn0wmad** [comment]
Closing for now
