### ISSUE TITLE
Backups Video

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#57]
How-to video on making backups, and equally importantly, WHY to make backups, on v0.3.x

- [x] Remote (CIFS)
- [x] Local

**Comment by BitcoinMechanic** [comment]
Ubuntu + MacOS done. Windows CIFS + Local remain.

**Comment by kn0wmad** [comment]
Video on local backups will close this ticket

**Comment by BitcoinMechanic** [comment]
Will be the next video
