### ISSUE TITLE
[feat]: Connecting Locally page should point Windows users to latest version of Bonjour

### ISSUE THREAD

**Issue by JesseMarkowitz** [Start9Labs/documentation#588]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Current instructions on https://docs.start9.com/0.3.5.x/user-manual/connecting-lan  point users to download version 2.0.2 of Bonjour.  They should provide information to download the latest version (version 3.1.0.1 as of now).

### Describe the Use Case

A user said this instantly fixed his mDNS issues

### Describe Preferred Solution

Here is a proposed replacement section for the current Windows only section.

​

Replace:

![image](https://github.com/Start9Labs/documentation/assets/1650462/e853124d-b9e5-419f-ba46-f4588bac7fa1)

with:

**Windows only**

On Windows, it is necessary to install Bonjour Service (mDNSResponder.exe) in order to access the .local URLs of your installed services. In a future release of StartOS, this will no longer be necessary.

1.    Go to https://www.apple.com/itunes/
2.    Ignore the option at the top to get the latest version from Microsoft store.  
![image](https://github.com/Start9Labs/documentation/assets/1650462/ada1f2d2-c935-4719-8544-aba415ebdcc4)
4.    Instead, scroll down and find the option: Looking for other versions? macOS> Windows >
5.    Click on "Windows >"
6.    You’ll still be on apple.com/itunes, but now it will give you the option to download
![image](https://github.com/Start9Labs/documentation/assets/1650462/f1b8a677-f868-401a-901e-2b31c144858c)
7.    Click on the download link to download “iTunes64Setup.exe”
8.    Using 7zip or winrar or similar program to open the “iTunes64Setup.exe” file
9.    Extract the “Bonjour64.msi” file
10.    Double click the “Bonjour64.msi” file and it will install on your computer
​

### Anything else?

May want to include screenshots of properties of the downloaded file:
![image](https://github.com/Start9Labs/documentation/assets/1650462/86a3f203-8763-4e8f-b909-e01b8d2ca339)

or of the service once installed:
![image](https://github.com/Start9Labs/documentation/assets/1650462/3de4338a-4a7e-4a4e-864d-9a64a5766bfd)

**Comment by kn0wmad** [comment]
Closed by #601
