### ISSUE TITLE
[bug]: Documentation on StartOS sounds does not include three beeps every 20-30 seconds

### ISSUE THREAD

**Issue by JesseMarkowitz** [Start9Labs/documentation#591]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Windows

### Device OS Version

Win10

### Browser

Chrome

### Browser Version

Version 121.0.6167.161 (Official Build) (64-bit)

### Current Behavior

https://docs.start9.com/0.3.5.x/support/common-issues#sounds-bepchime includes 4 sounds (bep, chime, flatline and Beethoven's 5th).  It should also include a fifth - Three beeps every 20-30 seconds means the server is starting up. When the server is updating to a new version or performing a system rebuild, it can go like that for a long time.

### Expected Behavior

Documentation to include the three beeps sound and description

### Steps to Reproduce

View https://docs.start9.com/0.3.5.x/support/common-issues#sounds-bepchime

**Comment by kn0wmad** [comment]
Would you be able to make a PR for this?

**Comment by gStart9** [comment]
Fixed by #586 and further by #613
