### ISSUE TITLE
Clicking the 3 lines on the top right within documentation is difficult on GrapheneOS

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/documentation#62]
Using Vanadium browser. I can get it to work it's just fiddly. Maybe the click area just needs to be larger? Works reliably on stock android.

**Comment by kn0wmad** [comment]
Tested this on Graphene/Vanadium as well as vanilla Android/Firefox and DDG browsers - it seems to work fine for me, but I could see how it could be larger for additional convenience.  I will see if this can be done easily, if not then we may close for now as a low priority
