### ISSUE TITLE
Create email sign-up on new landing page

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#63]
To be on listserve for updates (namely 0.3)

**Comment by elvece** [comment]
Completed [here](https://github.com/Start9Labs/documentation/pull/49/commits/5a649f6c5abe77c34da2ac1518dd33efa24dbe7a)

**Comment by elvece** [comment]
To be clear: this is subscribing via shopify. I just noticed this ticket says listserv, but I am not sure what that is. Does this need to be updated to reflect that change yet? @kn0wmad 

If not, could you please test @kn0wmad ? I believe Kiara should be able to verify that the email is now registered in shopify.

**Comment by kn0wmad** [comment]
Is Shopify the way that current emails are collected?  If so, then this is fine for the time being and we can change over after publishing.  We have new self-hosted email software, but it needs a couple things more and is a lower priority atm

**Comment by kn0wmad** [comment]
Completed in #49
