### ISSUE TITLE
Edit/Update dev docs

### ISSUE THREAD

**Issue by elvece** [Start9Labs/documentation#66]
- [x] edit content for correctness
- [x] add details on config options
- [x] add details on backups options
- [x] add details on use of system images
- [x] ensure hello world can be deployed

**Comment by 2-Watts** [comment]
404 error: broken link,  referenced from within eos.v0.3.0 :  
http://embassy.local/#/recover
pointing to: 
https://docs.start9.com/user-manual/general/backups#shared-network-folder
404
We cannot find what you are looking for!

steps to reproduce:
1) fresh build (Feb 7)  of 0.3.0, deployed onto raspberry pi 4 
2) Browse/navigate to : 
http://embassy.local
3) add product key. 
4) select "RECOVER" button.
5) use 'instructions' hyperlink, found on page:
http://embassy.local/#/recover

**Comment by kn0wmad** [comment]
> 404 error: broken link, referenced from within eos.v0.3.0 : http://embassy.local/#/recover pointing to: https://docs.start9.com/user-manual/general/backups#shared-network-folder 404 We cannot find what you are looking for!
> 
> steps to reproduce:
> 
>     1. fresh build (Feb 7)  of 0.3.0, deployed onto raspberry pi 4
> 
>     2. Browse/navigate to :
>        http://embassy.local
> 
>     3. add product key.
> 
>     4. select "RECOVER" button.
> 
>     5. use 'instructions' hyperlink, found on page:
>        http://embassy.local/#/recover
>        ![Screenshot at 2022-02-07 15:14:02](https://user-images.githubusercontent.com/42248238/152890545-76a6a3d4-de45-437d-96cb-3d9eca69f90d.png)
>        r

Hi there.  Appreciate the find - we have not yet edited the UI external links as this requires us to launch the new website/docs first.  The ticket is here https://github.com/Start9Labs/embassy-os/issues/363

**Comment by elvece** [comment]
All tasks completed, closing.
