### ISSUE TITLE
Lefthand menu does not display as expected

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#70]
Shows too many pages rather than nesting them in a collapsed menu

![image](https://user-images.githubusercontent.com/39687477/150850392-dbd4e3be-4e3b-4deb-bcbb-0cf863285754.png)

**Comment by elvece** [comment]
Fixed [here](https://github.com/Start9Labs/documentation/commit/889f143e224b825836f080b7c7d3cb25362b5b66)
