### ISSUE TITLE
Bug in top nesting menu

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#71]
The 'Support' folder shows when on it's index, but does not show when visiting a page nested within it

![image](https://user-images.githubusercontent.com/39687477/150850638-2f5fe686-0260-40f1-834d-1f4f099f762a.png)

![image](https://user-images.githubusercontent.com/39687477/150850707-d30e32fa-ac23-431a-8109-3c08fe587f6e.png)

**Comment by elvece** [comment]
Fixed as a result of fixing [this](https://github.com/Start9Labs/documentation/issues/70)
