### ISSUE TITLE
Clicking an internal ref bug

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#73]
Visiting an internal reference results in landing on the page with the desired ref obscured underneath the header.  In the below example, the ref visited was "Product Key" which is buried underneath the header and therefore it is not obvious that you are in the right place on arrival.

![image](https://user-images.githubusercontent.com/39687477/151413461-1633bcb4-8986-4ec7-a6c8-56e7758b421f.png)

**Comment by elvece** [comment]
Fixed [here](https://github.com/Start9Labs/sphinx-scylladb-theme/commit/75c644652b7df4bf796ac8a4fb4adbce55e2ce9a)
