### ISSUE TITLE
Menu expansion arrows are tiny

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#74]
Would be nice to increase clickable area.  This is most annoying on a laptop.  Not sure if even possible.  Low priority

![image](https://user-images.githubusercontent.com/39687477/151429391-1273e7e7-af37-45e7-b322-d3c0911dbc7a.png)

**Comment by elvece** [comment]
Fixed [here](https://github.com/Start9Labs/sphinx-scylladb-theme/commit/9b2c03817ffc36aee214577baac80dea22b7e581)
