### ISSUE TITLE
Guide for making a channel with S9

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#75]
Include parameters on opening a channel. Open a private channel for small amounts, open a public channel for > 10mln sats, and to please contact us for further info

**Comment by kn0wmad** [comment]
Maybe also a modern video?

**Comment by BitcoinMechanic** [comment]
Hopefully fixed by https://github.com/Start9Labs/documentation/pull/302

(Not video, just written guide)

**Comment by BitcoinMechanic** [comment]
Closing - will make a new issue for the eventual video guide.
