### ISSUE TITLE
/etc/embassy: No such file or directory

### ISSUE THREAD

**Issue by DrewAns** [Start9Labs/documentation#88]
On this page of the developer docs
https://start9.com/latest/developer-docs/getting-started/sdk
unless you mkdir etc/embassy, the command
chown <user> /etc/embassy
will throw an issue saying no such file or directory.

It might be helpful to the end user to add a step to create this directory.

**Comment by kn0wmad** [comment]
What is this in reference to?  Can you give a page / line please?

**Comment by ProofOfKeags** [comment]
This ticket does not meet the minimum level of description required for anyone to do anything about it @DrewAns

**Comment by kn0wmad** [comment]
Closing due to lack of information
