### ISSUE TITLE
Minor Correction to FAQ Page

### ISSUE THREAD

**Issue by NyamiDev** [Start9Labs/documentation#9]
Hi, 

Firstly thanks for a great product. Might be worth updating the last paragraph of your FAQ page to say that you can use your own RPi. Minor I know but it can throw people. This is the current text:

"Is it possible to DIY the EmbassyOS on my own hardware?¶

In the near future, you will be able to purchase EmbassyOS from us online. This will be great for people who already own the necessary hardware or who live outside the US and want to save on shipping and customs fees."

Good luck!

Nyami

**Comment by elvece** [comment]
Hi @NyamiDev! Thanks for pointing this out. Fixing now.
