### ISSUE TITLE
Setup instructions for trusting Embassy CA over LAN not working for Chrome and Safari for Mac

### ISSUE THREAD

**Issue by cryptodread** [Start9Labs/documentation#93]
When trying to set it up on Chrome for Mac, the instructions are not working.

When trying to go to chrome://settings/certificates - it does not take them to the same page displayed in the instructions screenshot
it actually re-directs you back to chrome://settings , and there is no authorities tab to click on.

Furthermore if you try and find the "manage certificates" section in chrome settings, it will take you to the OS certificates window, not the browser one.

**Comment by BitcoinMechanic** [comment]
I believe once the root CA is imported into the Keychain Access, and all settings changed to "Always Trust", then the browser restarted (either Brave/Safari/Chrome) it should work correctly.

Only Firefox has an option to further add the cert within the browser itself.

**Comment by BitcoinMechanic** [comment]
OS X stuff can be hard to repro because stuff changes to much from version to version.

**Comment by kn0wmad** [comment]
> I believe once the root CA is imported into the Keychain Access, and all settings changed to "Always Trust", then the browser restarted (either Brave/Safari/Chrome) it should work correctly.
> 
> Only Firefox has an option to further add the cert within the browser itself.

This was my understanding.  Can you verify this so we can adjust the docs?

**Comment by ProofOfKeags** [comment]
> Only Firefox has an option to further add the cert within the browser itself.

Brave does as well.

**Comment by BitcoinMechanic** [comment]
@ProofOfKeags Are you sure Brave does this? I can only get it to open Keychain Access. It's potentially different on a Mac.

**Comment by BitcoinMechanic** [comment]
To be clear - we're talking about this
<img width="1680" alt="Screen Shot 2022-03-15 at 2 11 35 PM" src="https://user-images.githubusercontent.com/45926711/158463249-af9465e0-9ba2-4486-9135-0ecfa355b743.png">
?

**Comment by BitcoinMechanic** [comment]
Can confirm that all three of Brave, Chrome and Safari connected properly via SSL from me just having added the root CA to Keychain Access - nothing needed to be done in any browser.

**Comment by kn0wmad** [comment]
Can you update docs to reflect please?

**Comment by BitcoinMechanic** [comment]
Can someone confirm to me what these browsers do on Windows/Linux?

**Comment by BitcoinMechanic** [comment]
Docs updated with https://github.com/Start9Labs/documentation/pull/97
