### ISSUE TITLE
Docs clearnet URL incorrectly resolves to onion URL with a period (".") in front

### ISSUE THREAD

**Issue by spencerflagg** [Start9Labs/documentation#99]
When navigating to https://start9.com/latest/user-manual/ssh in the TOR Browser the clearnet URL eventually resolves to an onion URL after a few seconds, but it looks like this: 
`http://.privacy34kn4ez3y3nijweec6w4g54i3g54sdv7r5mr6soma3w4begyd.onion//latest/user-manual/ssh`
with a period in front of the domain.

(Removing the period, of course, brings me to the right page.)

_I arrived at this page via the link at the top of the SSH Keys UI in EmbassyOS - but I don't think it matters, as the clearnet page had already loaded correctly before the browser redirected it._

- **TOR Browser 11.0.7**
- **Pop!_OS 21.10**

**Comment by ProofOfKeags** [comment]
I think only the . needs to be removed. the // should remain.

**Comment by kn0wmad** [comment]
> I think only the . needs to be removed. the // should remain.

This is the `//` following `.onion` - not the `//` trailing `http:`

**Comment by gStart9** [comment]
To characterize this a little more clearly:

When you load any page @ https://start9.com

Nginx serves the Onion-Location header pointing to the .onion alternative URL, but renders it incorrectly:
1. It starts with a .
2. There are 2 slashes after onion (likely from nginx config concatenating "....onion/" + path

Example:

Onion-Location: http://.privacy34kn4ez3y3nijweec6w4g54i3g54sdv7r5mr6soma3w4begyd.onion//latest/user-manual/ssh

Fix:
1. If subdomain is null, strip leading .
2. Change onion url to end at ".onion" (exclude trailing slash)

**Comment by elvece** [comment]
Both issues resolved in nginx config
